data_path: ${DATA_PATH}

task: phase_segmentation
scope: all
datasets:
  - cataract-101
  - cataract-21


val_split: 0.2

downsample_stride: 6

model: ms_tcn

tcn:
  num_stages: 4
  num_layers: 10
  num_filters: 64

batch_size: 1
num_epochs: 20

device: mps