task: phase_segmentation
scope: single

dataset: cataract-21

video_path: ~/.opticai-data/cataract-21/training/case_10.mp4

model: ms_tcn

checkpoint: outputs/phase_segmentation/models/best.pt

tcn:
  num_stages: 4
  num_layers: 10
  num_filters: 64

downsample_stride: 4

device: mps